### ISSUE TITLE
Add Fly.io

### ISSUE THREAD

**Issue by lubien** [viniciusgabrielfo/empresas-golang#9]
https://fly.io/jobs/

Golang faz boa parte dos jobs de platform engineer.

Sinceramente eu ia contribuir mas a formatação da tabela me fez desistir 😓

**Comment by viniciusgabrielfo** [comment]
Entendo :(

Vou abrir um PR assim que possível adicionando, agradeço! 

Tem alguma sugestão de como poderia ficar mais fácil a contribuição talvez?

**Comment by lubien** [comment]
@viniciusgabrielfo nao consigo lembrar o motivo da frustracao mas tentei denovo pra reproduzir e dessa vez consegui
